---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-rest
  labels:
    app: spring-petclinic-rest
spec:
  type: NodePort
  selector:
    app: spring-petclinic-rest
  ports:
  - protocol: TCP
    port: 9966
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-rest
spec:
  selector:
    matchLabels:
      app: spring-petclinic-rest
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-petclinic-rest
    spec:
      containers:
      - name: spring-petclinic-rest
        image: jacyzin/spring-petclinic-rest:1.0
        ports:
        - containerPort: 9966
        livenessProbe:
          httpGet:
            path: /health
            port: 9966
          initialDelaySeconds: 30
          timeoutSeconds: 1